// Fallback jobs data — used when scraper returns zero results
const fallbackJobs = [
  {
    id: "fallback-1",
    title: "Frontend Developer (React)",
    company: "TCS",
    location: "Bangalore, India",
    type: "Full-time",
    experienceLevel: "Experienced",
    category: "Software Engineering",
    salary: "Competitive",
    postedAt: "Recently",
    source: "Fallback",
    logo: "[TC]",
    skills: ["React", "JavaScript", "CSS"],
    url: "https://www.tcs.com/careers",
  },
  {
    id: "fallback-2",
    title: "Node.js Backend Engineer",
    company: "Infosys",
    location: "Pune, India",
    type: "Full-time",
    experienceLevel: "Experienced",
    category: "Software Engineering",
    salary: "Competitive",
    postedAt: "Recently",
    source: "Fallback",
    logo: "[IN]",
    skills: ["Node.js", "Express", "PostgreSQL"],
    url: "https://www.infosys.com/careers",
  },
  {
    id: "fallback-3",
    title: "Full Stack Developer",
    company: "Wipro",
    location: "Hyderabad, India",
    type: "Full-time",
    experienceLevel: "Experienced",
    category: "Software Engineering",
    salary: "Competitive",
    postedAt: "Recently",
    source: "Fallback",
    logo: "[WI]",
    skills: ["React", "Node.js", "MongoDB"],
    url: "https://careers.wipro.com/",
  },
];

module.exports = { fallbackJobs };
